### ISSUE TITLE
Styles optional/loaded after vuepress styles

### ISSUE THREAD

**Issue by travispamaral** [vue-styleguidist/vuepress-plugin-live#10]
Hi there! I just started using this and Im quickly finding I don't really need these defined styles. Im not sure how Vuepress plugins work but is there anyway to allow these to be optional or more easy to overwrite/remove? Adding `!important` to every declaration seems like a lot.

https://github.com/vue-styleguidist/vuepress-plugin-live/blob/master/layout.vue#L12

Thanks! Great work 👍🏼

**Comment by f3ltron** [comment]
Hello thank's for using it :)

Do you have a repo to try it ?

**Comment by elevatebart** [comment]
Hey @travispamaral 

Thank you for your interest in the plugin.
We could add an option to load the layout component yourself.
Would that solve your issue?

**Comment by elevatebart** [comment]
@f3ltron 
[In this file](https://github.com/vue-styleguidist/vuepress-plugin-live/blob/master/vueLiveWithLayout.js#L14) I would change the layout to become an optional prop of the component and change enhanceAppFiles.js to specify where to find the layout if provided.

**Comment by travispamaral** [comment]
@f3ltron I unfortunately am implementing in a private repo so I cannot share.

@elevatebart that would be a great addition! I think having the ability to choose whether or not users can implement their own layout/styles or use the default would be a huge help.

**Comment by f3ltron** [comment]
ok @elevatebart  i could propore something for that.

Maybe they just want to update a part of the css now ?

**Comment by elevatebart** [comment]
@travispamaral I delivered the feature, I hope you like it ;)

**Comment by travispamaral** [comment]
@elevatebart you rock! Thanks so much, I was going to try and PR the change over the weekend but couldn't get to it. Thanks again 🎉
