### ISSUE TITLE
Is it possible to disable parsing of import statement?

### ISSUE THREAD

**Issue by freearhey** [vue-styleguidist/vuepress-plugin-live#14]
Here is an example of what I need to display:

```vue
<template>
  <vue-button>Button</vue-button>
</template>

<script>
import { Button } from 'some-package'

export default {
  components: {
    [Button.name]: Button
  }
}
</script>
```

The problem is that when `import ...` is displayed in the editor, errors begin to appear and half of the tags are highlighted in white.

**Comment by freearhey** [comment]
Ok, how to fix errors I figured out. 

In my case, I simply uninstalled the `@vuepress/plugin-register-components` plugin and used the `.vuepress / enhanceApp.js` file to register the components.

But I still don’t understand why `import` makes all HTML tags in the editor highlight white. Any ideas?

**Comment by f3ltron** [comment]
maybe because he is waiting for nodejs require and not import

**Comment by freearhey** [comment]
I found exactly what the problem is, and this is my mistake. I just forgot that in one of the components there are styles for the CSS class "tag" and, coincidentally, all the HTML tags in the editor are marked in the same way.
