### ISSUE TITLE
Code Copy Removed

### ISSUE THREAD

**Issue by germanbobadilla** [vue-styleguidist/vuepress-plugin-live#19]
After enabling the plugin, my code copy plugin gets smashed in the editor, and the success text appears on my previewed code. What can I do? How can I disable code-copy from here?
![Capture](https://user-images.githubusercontent.com/14115887/79639252-9d09ed00-8158-11ea-91a9-c243b5d35b10.PNG)

**Comment by elevatebart** [comment]
Hello @germanbobadilla 

Thank you for reaching out.

I see two issues here: 

1. I probably should use `overflow-x: auto` to avoid the code getting out of the frame.
1. The plugin you are using is incompatible with this one.

Do you mind sharing the link to the other plugin you are using?

**Comment by germanbobadilla** [comment]
https://github.com/znicholasbrown/vuepress-plugin-code-copy

**Comment by elevatebart** [comment]
Have you tried changing the [selector option](https://github.com/znicholasbrown/vuepress-plugin-code-copy#selector) of your copy plugin?
It could, for instance, ignore the editors that are live.

**Comment by elevatebart** [comment]
Hello @germanbobadilla , 

I created #20 to illustrate what I meant. I hope it helps you understand what I mean.
If you would like to add a copy button to your editors, I can help you create a Pull Request here and we could have an option to create this copy button here.

I think it would be an option a lot of people would find useful.
