### ISSUE TITLE
Prism editor broken with latest vue-live.

### ISSUE THREAD

**Issue by Decipher** [vue-styleguidist/vuepress-plugin-live#25]
It appears that vue-live has been updated for the latest vue-prism-editor release, which results in a visible Textarea when using this plugin.

**Comment by elevatebart** [comment]
Should be fixed momentarily

**Comment by elevatebart** [comment]
fixed in 1.16

**Comment by Decipher** [comment]
Thanks, appreciate the promptness and the module(s).
