### ISSUE TITLE
vuepress prism syntax-highlight is broken after vue-live component is loaded

### ISSUE THREAD

**Issue by tlyau62** [vue-styleguidist/vuepress-plugin-live#47]
Before vue-live's component is loaded, the prism syntax highlight works fine in other places at the same markdown.

![image](https://user-images.githubusercontent.com/24647774/138440817-5d2526da-1804-418f-a531-b5f90faf32f0.png)

But, it fails after the vue-live component is loaded.

![image](https://user-images.githubusercontent.com/24647774/138440893-7e38c2ca-af36-4c71-ae97-3a53e18139f0.png)

**Comment by Kolobok12309** [comment]
@tlyau62 Big thanks, it fix `ts` highlight in code, i think it fix all other languages except `'markup', 'css', 'javascript'`(their preloaded)
